---
title: "Exploration"
author: "Ibrahim Al-Hindi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Libraries
library(tidyverse)
library(here)
library(lubridate)
library(ggmap)
library(tidytransit)
library(sf)
library(plotly)
```

```{r}
# GTFSr Data
updates_raw <- read_csv(here("data/GTFSr/large/gtfsr_prod.trip_updates.SAMPLE.csv.csv"))
positions_raw <- read_csv(here("data/GTFSr/large/gtfsr_prod.vehicle_positions.SAMPLE.csv.csv"))
stops_raw <- read_csv(here("data/GTFS_feed_version_1175/stops.csv"))
routes_raw <- read_csv(here("data/GTFS_feed_version_1175/routes.csv"))
trips_raw <- read_csv(here("data/GTFS_feed_version_1175/trips.csv"))
shapes_raw <- read_csv(here("data/GTFS_feed_version_1175/shapes.csv"))
sites_raw <- read_csv(here("data/addinsight/addinsight_prod.btsites.csv.csv"))
```

## Data Wrangling

### Updates

```{r}
# Updates
updates <- updates_raw %>% 
  # The same trip on the same date for the same stop can have multiple delay updates,
  # therefore filter updates to the most recent timestamp
  group_by(across(c(-timestamp, -delay, -arrival_time))) %>% 
  filter(timestamp == max(timestamp)) %>% 
  ungroup() %>% 
  mutate(direction_id = factor(direction_id, levels = c(1, 0)),
         start_date = ymd(start_date),
         label = as.character(label),
         wheelchair_accessible = factor(wheelchair_accessible, levels = c(1, 0)),
         timestamp = as_datetime(timestamp),
         id = as.character(id),
         stop_id = as.character(stop_id),
         arrival_time = as_datetime(arrival_time),
         date = date(timestamp),
         wday = wday(timestamp, label = TRUE, abbr = TRUE, week_start = 1),
         hour = hour(timestamp),
         time_stamp_floor = floor_date(timestamp, unit = "hour")) %>% 
  rename(trip_id = id,
         vehicle_id = label)

# Remove original updates file
rm(updates_raw)

# Positions
positions <- positions_raw %>% 
  mutate(trip_id = as.character(trip_id),
         start_date = ymd(start_date),
         direction_id = factor(direction_id, levels = c(1, 0)),
         vehicle_id = as.character(vehicle_id),
         wheelchair_accessible = factor(wheelchair_accessible, levels = c(1, 0)))

rm(positions_raw)

# Routes
routes <- routes_raw %>% 
  select(route_id, route_long_name:route_type, route_color, routegroup) %>% 
  mutate(route_color = paste0("#", route_color))

rm(routes_raw)

# Stops
stops <- stops_raw %>% 
  mutate(stop_id = as.character(stop_id)) %>% 
  select(stop_id:stop_lon)

rm(stops_raw)

# Trips
trips <- trips_raw %>% 
  mutate(trip_id = as.character(trip_id)) %>%
  mutate(shape_id = as.character(shape_id)) %>% 
  select(service_id:trip_headsign, block_id:shape_id)

rm(trips_raw)

# shapes
shapes <- shapes_raw %>% 
  mutate(shape_id = as.character(shape_id)) %>% 
  select(shape_id:shape_dist_traveled)
  

rm(shapes_raw)

# Join
combined <- updates %>% 
  left_join(stops, by = "stop_id") %>% 
  left_join(routes, by = "route_id") %>% 
  left_join(trips, by = "trip_id") %>% 
  # filter to buses only
  filter(route_type == 3) %>% 
  # create minutes column
  mutate(delay_minutes = delay/60, .after = delay)
```


## Exploration

### Updates

```{r}
# Updates Understanding the data
## trip_id can occur in different dates using different vehicles, might be unique for each start_time
# updates %>%
#   group_by(trip_id) %>% 
#   summarise(
#     routes = n_distinct(route_id),
#     directions = n_distinct(direction_id),
#     dates = n_distinct(start_date),
#     vehicles = n_distinct(vehicle_id),
#     all = n_distinct(route_id, direction_id, start_date, vehicle_id)) %>% 
#   arrange(-directions)

# Multiple vehicles can do the same trip on the same day
# need start_time
combined %>% 
  group_by(trip_id, start_date, direction_id) %>% 
  summarise(n = n_distinct(vehicle_id)) %>% 
  arrange(-n)

## Multiple trip_id can occur using the same combination of variables in group_by,
## need start_time
updates %>% 
  group_by(route_id, direction_id, start_date, vehicle_id) %>% 
  summarise(trips = n_distinct(trip_id)) %>% 
  arrange(-trips)
```

```{r}
# delay per date and weekday
combined %>% 
  group_by(date, wday) %>% 
  summarise(avg_delay = mean(delay_minutes)) %>% 
  ggplot(aes(x = date, y = avg_delay)) +
  geom_line(size = 2, alpha = 0.2) +
  geom_line(aes(color = wday)) +
  scale_color_brewer(type = "qual")

# delay per weekday
combined %>% 
  group_by(wday) %>% 
  summarise(avg_delay = mean(delay_minutes)) %>% 
  ggplot(aes(x = wday, y = avg_delay)) +
  geom_col()
```

Barely any delays

```{r}
# # Delays per stop
# stops_delays <- updates %>% 
#   group_by(stop_id) %>% 
#   summarise(avg_delay = mean(delay),
#             no_of_trips = n(),
#             no_of_routes = n_distinct(route_id)) %>% 
#   mutate(delay_mins = avg_delay/60) %>% 
#   arrange(-avg_delay)
# 
# # Select top 13 stop_id's because the number of routes is 1 so it's easier to obtain
# # the route description
# top10_delays <- stops_delays %>% 
#   slice_head(n = 13) %>% 
#   # Filter out train substitute services
#   filter(stop_id %in% c(107, 130, 141, 79, 86))
# 
# # Delays per stop and hour
# stops_hours_delays <- updates %>% 
#   group_by(stop_id, hour) %>% 
#   summarise(avg_delay = mean(delay)) %>% 
#   mutate(delay_mins = avg_delay/60) %>% 
#   arrange(-avg_delay)
# 
# shd_over1hr <- stops_hours_delays %>% 
#   filter(delay_mins >= 60) %>% 
#   # 1pm has the most delays
#   filter(hour == 13)
# 
# # Extract trips that have the stops above at 1pm
# updates %>% 
#   semi_join(shd_over1hr)
# # The culprit is one trip on 6/1/2022. Ignore
# # This method is not good, try switching back to delays per stop
# 
# # Pick one of the stops to investigate
# stop_107 <- updates %>% 
#   filter(stop_id == 107)
# # The same trip on the same date for the same stop can have multiple delay updates,
# # therefore filter updates to the most recent timestamp. This will be done in the
# # data cleaning chunk above.
# 
# 
# # Filter updates to contain the top10 stops above
# updates %>% 
#   semi_join(top10_delays) %>%
#   ggplot(aes(x = timestamp, y = delay, color = stop_id)) +
#   geom_line()
```

## Delays

### Delays per Stop

```{r}
stops_delays <- combined %>% 
  # Remove exceptional cases
  filter(!(stop_id %in% c("3387", "975", "100781", "100873", "100871", "2063", "6174") & delay_minutes > 40)) %>%
  group_by(stop_id) %>% 
  summarise(avg_delay = mean(delay_minutes),
            occurences = n(),
            no_of_routes = n_distinct(route_id),
            route_id = unique(route_id)) %>%
  ungroup() %>% 
  arrange(-avg_delay)

# Select top delays per stop_id
top_stops_delays <- stops_delays %>%
  # Exclude stops with low occurrences
  filter(occurences > 49) %>% 
  left_join(routes, by = "route_id") %>% 
  select(stop_id:route_id, route_desc) %>%
  # Filter out routes that are train substitutes or hail n' rides
  filter(!str_detect(tolower(route_desc), pattern = "train substitute service|hail")) %>% 
  distinct(stop_id, .keep_all = TRUE) %>% 
  slice_head(n=5)

stops_combined <- combined %>% 
  semi_join(top_stops_delays, by = "stop_id")

stops_combined %>% 
  ggplot(aes(x = timestamp, y = delay_minutes, color = stop_id)) +
  geom_point() +
  geom_line()
```

## Delays per Route

```{r}
# routes_delays <- combined %>% 
#   # Remove exceptional cases
#   filter(!(route_id %in% c("238", "415H", "500", "835", "224M") & delay_minutes > 40)) %>% 
#   group_by(route_id) %>% 
#   summarise(avg_delay = mean(delay_minutes),
#             occurrences = n(),
#             route_name = unique(route_long_name),
#             route_desc = unique(route_desc),
#             route_group = unique(routegroup),
#             route_color = unique(route_color)) %>%
#   ungroup() %>%
#   # Filter out routes that are train substitutes or hail n' rides
#   filter(!str_detect(tolower(route_desc), pattern = "train substitute|hail"),
#          # Exclude routes with low occurrences
#          occurrences > 99) %>% 
#   arrange(-avg_delay)

routes_delays <- combined %>%
  # Remove exceptional cases
  filter(!(route_id %in% c("224M", "225M", "750B", "864", "743") & delay_minutes > 40),
         # Filter out routes that are train substitutes or hail n' rides
         !str_detect(tolower(route_desc), pattern = "train substitute|hail")) %>% 
  group_by(route_id) %>%
  summarise(avg_delay = mean(delay_minutes),
            no_of_trips = n_distinct(trip_id),
            route_name = unique(route_long_name),
            route_desc = unique(route_desc),
            route_group = unique(routegroup),
            route_color = unique(route_color)) %>%
  ungroup() %>%
  # Only include routes with number of trips greater than the median, indicates
  # abundance of data and importance of route
  filter(no_of_trips > median(no_of_trips)) %>%
  arrange(-avg_delay)

# top 5 routes delays
top_routes_delays <- routes_delays %>% 
  slice_head(n=5)

routes_combined <- combined %>% 
  semi_join(top_routes_delays, by = "route_id")

ggplot(routes_combined, aes(x = timestamp, y = delay_minutes, color = route_id)) +
  geom_point() +
  geom_line()
```

## Delays per Hour

```{r}
hourly_delays <- combined %>%
  group_by(hour) %>% 
  summarise(avg_delay = mean(delay_minutes),
            occurrences = n()) %>%
  ungroup() %>%
  arrange(-avg_delay)

ggplot(hourly_delays, aes(hour, avg_delay)) +
  geom_line() +
  scale_x_continuous(breaks = seq(0,23)) +
  theme(panel.grid.minor = element_blank())
```

### Delays per Route per Hour
```{r}
routes_hourly_delays <- combined %>%
  group_by(route_id, hour) %>% 
  summarise(avg_delay = mean(delay_minutes),
            occurrences = n(),
            no_of_trips = n_distinct(trip_id),
            route_name = unique(route_long_name),
            route_desc = unique(route_desc),
            route_group = unique(routegroup),
            route_color = unique(route_color)) %>%
  ungroup() %>%
  # Filter out routes that are train substitutes or hail n' rides
  filter(!str_detect(tolower(route_desc), pattern = "train substitute|hail")) %>% 
  arrange(-avg_delay)

mean(routes_hourly_delays$occurrences)
```













# Map

```{r}
# Obtain shapes required per shape_id in stops_combined
stops_shapes <- shapes %>% 
  semi_join(stops_combined, by = "shape_id") %>% 
  arrange(shape_id, shape_pt_sequence)

stops_shapes_sf <- st_as_sf(stops_shapes, coords = c("shape_pt_lat", "shape_pt_lon"))

# Map method 1
ggplot() +
  geom_path(data = shapes, aes(shape_pt_lon, shape_pt_lat, group=shape_id), size=.2, alpha=.1) +
  coord_fixed()

# Map method 2
bbox <- c(138.454415,-35.206164,138.742257,-34.660694)

ggplot(stops_shapes_sf) +
  geom_sf(data = stops_shapes_sf, aes(color = shape_id))
```








```{r}
stops_combined %>% 
  group_by(route_id, direction_id, service_id) %>% 
  summarise(n = n_distinct(shape_id)) %>% 
  arrange(-n)
```





















```{r}
# Coordinates retrieved from https://www.openstreetmap.org/export#map=12/-34.6943/138.6887
ints_map <- get_map(c(left = 138.4387,
                      bottom = -35.2546,
                      right = 138.7628,
                      top = -34.6648),
                    source = "stamen")

# sites and top stops locations
ggmap(ints_map) +
  geom_point(data = stops_combined, aes(x = stop_lon, y = stop_lat), color = "red", alpha = 0.3, size = 2) +
  geom_point(data = sites_raw, aes(x = longitude, y = latitude), color = "blue", alpha = 0.3, size = 2) +
  theme_void()


```











































