# Analysis

## Calculations

### Trip Times

```{r}
# Ceiling date by aggregate duration. Get time and weekday
trip_times_agg <- trip_times %>% 
  mutate(arrival_time = ceiling_date(arrival_time, "15 mins")) %>% 
  mutate(time = hms::as_hms(arrival_time), .after = arrival_time)

# Without direction

# ## Average delay per stop per timestamp
# stop_delay_stamp <- delays_agg %>%
#   group_by(timestamp, stop_id) %>%
#   summarise(avg_delay = mean(stop_delay)) %>%
#   ungroup()

## Average trip time per aggregated arrival_time
trip_time_arrival <- trip_times_agg %>%
  group_by(arrival_time) %>%
  summarise(avg_time = mean(trip_time)) %>%
  ungroup()

# ## Average delay per stop per time
# stop_delay_time <- delays_agg %>% 
#   group_by(time, stop_id) %>% 
#   summarise(avg_delay = mean(stop_delay)) %>% 
#   ungroup()

## Average trip time per time (hour and minute of the day)
trip_time_hm <- trip_times_agg %>%
  group_by(time) %>% 
  summarise(avg_time = mean(trip_time)) %>% 
  ungroup()

# With direction

# ## Average delay per stop per timestamp per direction
# stop_delay_stamp_dir <- delays_agg %>%
#   group_by(timestamp, stop_id, direction) %>%
#   summarise(avg_delay = mean(stop_delay)) %>%
#   ungroup()

## Average trip time per aggregated arrival_time per direction
trip_time_arrival_dir <- trip_times_agg %>%
  group_by(arrival_time, direction) %>%
  summarise(avg_time = mean(trip_time)) %>%
  ungroup()

# ## Average delay per stop per time per direction
# stop_delay_time_dir <- delays_agg %>%
#   group_by(time, stop_id, direction) %>% 
#   summarise(avg_delay = mean(stop_delay)) %>% 
#   ungroup()

## Average delay of all stops per time per direction (average full road delay by direction)
trip_time_hm_dir <- trip_times_agg %>%
  group_by(time, direction) %>% 
  summarise(avg_time = mean(trip_time)) %>% 
  ungroup()
```

### Congestion

```{r}
links_agg <- link_stats  %>% 
  mutate(logtime = ceiling_date(logtime, "15 mins")) %>% 
  mutate(time = hms::as_hms(logtime), .after = logtime)

# Average congestion per link per logtime per direction
ind_link_cong_logtime <- links_agg %>%
  group_by(logtime, direction, linkid) %>%
  summarise(avg_congestion = mean(congestion)) %>%
  ungroup()

# Average congestion of all links per logtime per direction (average full road congestion)
links_cong_logtime <- links_agg %>%
  group_by(logtime, direction) %>%
  summarise(avg_congestion = mean(congestion))

# Average congestion per link per time
ind_link_cong_time <- links_agg %>% 
  group_by(time, linkid, direction) %>% 
  summarise(avg_congestion = mean(congestion)) %>% 
  ungroup()

# Average congestion of all links per time (average full road congestion)
links_cong_time <- links_agg %>% 
  group_by(time, direction) %>% 
  summarise(avg_congestion = mean(congestion))
```

## Compare

```{r}
compare_trips_links <- function(timeframe = "15 minutes", plot = "line", measure = congestion){
  trip_times_agg <- trip_times %>% 
  mutate(arrival_time = ceiling_date(arrival_time, timeframe)) %>% 
  mutate(time = hms::as_hms(arrival_time), .after = arrival_time)

  links_agg <- link_stats  %>% 
  mutate(logtime = ceiling_date(logtime, timeframe)) %>% 
  mutate(time = hms::as_hms(logtime), .after = logtime)

  if (plot == "line") {
    
      trip_time_hm_dir <- trip_times_agg %>%
        group_by(time, direction) %>% 
        summarise(avg_time = mean(trip_time)) %>% 
        ungroup()
      
      links_cong_time <- links_agg %>% 
        group_by(time, direction) %>% 
        summarise(avg_congestion = mean({{measure}}))
      
      trip_time_cong_links <- trip_time_hm_dir %>% 
        full_join(links_cong_time)

      trip_time_cong_links_pivot <- trip_time_cong_links %>%
        pivot_longer(cols = avg_time:avg_congestion, names_to = "stat", values_to = "value") %>% 
        mutate(direction = recode(direction, from_city = "From City", to_city = "To City"),
               stat = recode(stat, avg_congestion = "Avg Congestion", avg_time = "Avg Time (secs)"))
      
      trip_time_cong_links_pivot_mor_rush <- trip_time_cong_links_pivot %>% 
        filter(between(time, as_hms("06:00:00"), as_hms("10:00:00")))
      
      trip_time_cong_links_pivot_eve_rush <- trip_time_cong_links_pivot %>% 
        filter(between(time, as_hms("15:00:00"), as_hms("19:00:00")))
      
      ggplot() +
        geom_line(data = trip_time_cong_links_pivot, aes(x = time, y = value), alpha = 0.2) +
        geom_line(data = trip_time_cong_links_pivot_mor_rush, aes(x = time, y = value), color = "blue", size = 0.5) +
        geom_line(data = trip_time_cong_links_pivot_eve_rush, aes(x = time, y = value), color = "blue", size = 0.5) +
        annotate("rect", xmin = as_hms("06:00:00"), xmax = as_hms("10:00:00"), ymin = -Inf, ymax = Inf,
        fill = "red", alpha = .1) +
        annotate("rect", xmin = as_hms("15:00:00"), xmax = as_hms("19:00:00"), ymin = -Inf, ymax = Inf,
        fill = "red", alpha = .1) +
        facet_grid(rows = vars(stat), cols = vars(direction), scales = "free_y") +
        scale_x_time(breaks = as_hms(c("00:00:00", "06:00:00", "08:00:00", "10:00:00", 
                                       "15:00:00", "17:00:00", "19:00:00")),
                     labels = c("00", "6", "8", "10", "15", "17", "19")) +
        labs(x = "Time", y = "") +
        theme_minimal()
  } else if (plot == "scatter") {
    
      trip_time_arrival_dir <- trip_times_agg %>%
        group_by(arrival_time, direction) %>%
        summarise(avg_time = mean(trip_time)) %>%
        ungroup()
      
      links_cong_logtime <- links_agg %>%
        group_by(logtime, direction) %>%
        summarise(avg_congestion = mean({{measure}}))
      
      trip_time_cong_links_scatter <- trip_time_arrival_dir %>% 
        inner_join(links_cong_logtime, by = c("arrival_time" = "logtime", "direction")) %>% 
        filter(between(as_hms(arrival_time), as_hms("06:00:00"), as_hms("10:00:00")) |
                 between(as_hms(arrival_time), as_hms("15:00:00"), as_hms("19:00:00"))) %>% 
         mutate(rush = if_else(between(as_hms(arrival_time), as_hms("06:00:00"), as_hms("10:00:00")),
                        "morning", "evening"))

      ggplot(trip_time_cong_links_scatter, aes(x = avg_congestion, y = avg_time)) +
        geom_point() +
        geom_smooth(se = FALSE) +
        facet_grid(vars(direction), vars(rush)) +
        labs(x = "Avg Congestion", y = "Avg Time (secs)") +
        theme_minimal()
  }
}
```

```{r}
compare_trips_links(timeframe = "30 minutes", measure = delay, plot = "scatter")
```



# Analysis 2

## Calculations

### Trip Times

```{r}
# Ceiling date by aggregate duration. Get time
trip_times_agg <- trip_times %>% 
  mutate(arrival_time = ceiling_date(arrival_time, "15 mins")) %>% 
  mutate(time = hms::as_hms(arrival_time), .after = arrival_time)
```


#### Without Direction (for Sites)

```{r}
# Average trip time and number of trips per aggregated arrival_time
trip_time_arrival <- trip_times_agg %>%
  group_by(arrival_time) %>%
  summarise(avg_time = mean(trip_time),
            no_trips = n(),
            rush = unique(rush)) %>%
  ungroup()

# Average trip time per time (hour and minute of the day)
trip_time_hm <- trip_times_agg %>%
  group_by(time) %>% 
  summarise(avg_time = mean(trip_time),
            no_trips = n(),
            rush = unique(rush),
            no_days = n_distinct(start_date),
            avg_per_day = no_trips/n_distinct(trip_times_agg$start_date)) %>% 
  ungroup()

# Average trip time per day per peak time
trip_times_peaks <- trip_times %>% 
  filter(rush %in% c("morning", "evening")) %>% 
  group_by(start_date, rush) %>% 
  summarise(avg_time_day = mean(trip_time)) %>% 
  ungroup() %>% 
  group_by(rush) %>% 
  mutate(avg_time_all_peak = mean(avg_time_day)) %>% 
  ungroup()

# Average trip time per day per peak time per hour
trip_times_peaks_hours <- trip_times %>% 
  filter(rush %in% c("morning", "evening")) %>%
  mutate(hour = hour(arrival_time)) %>% 
  group_by(start_date, rush, hour) %>% 
  summarise(avg_time = mean(trip_time)) %>% 
  ungroup() %>% 
  group_by(rush, hour) %>% 
  mutate(avg_time_all = mean(avg_time)) %>% 
  ungroup()

# Day with largest trip time per hour
trip_times_peaks_hours_largest_day <- trip_times_peaks_hours %>% 
  group_by(rush, hour) %>% 
  filter(avg_time == max(avg_time)) %>% 
  ungroup()
```

```{r}
ggplot(filter(trip_time_hm, rush == "neither"), aes(x = time, y = avg_per_day)) +
  geom_col(color = "grey", alpha = 0.3) +
  geom_col(data = filter(trip_time_hm, rush %in% c("morning", "evening")), color = "grey") +
  scale_x_time(breaks = as_hms(c("00:00:00", "06:00:00", "08:00:00", "10:00:00",
                                 "15:00:00", "17:00:00", "19:00:00")),
               labels = c("00", "6", "8", "10", "15", "17", "19")) +
  theme_minimal()

ggplot(trip_times_peaks, aes(start_date, avg_time_day)) +
  geom_line() +
  geom_point() +
  geom_hline(aes(yintercept = avg_time_all_peak), linetype = "dashed", color = "red") +
  facet_wrap(vars(rush), scales = "free_y") +
  theme_minimal()

trip_times_peaks_hours %>% 
  filter(rush == "morning") %>% 
  ggplot(aes(start_date, avg_time)) +
  geom_line() +
  geom_point() +
  geom_hline(aes(yintercept = avg_time_all), linetype = "dashed", color = "red") +
  facet_wrap(vars(hour), scales = "free_y") +
  theme_minimal()

trip_times_peaks_hours %>% 
  filter(rush == "evening") %>% 
  ggplot(aes(start_date, avg_time)) +
  geom_line() +
  geom_point() +
  geom_hline(aes(yintercept = avg_time_all), linetype = "dashed", color = "red") +
  facet_wrap(vars(hour), scales = "free_y") +
  theme_minimal()

trip_times_peaks_hours_largest_day %>% 
  ggplot(aes(hour, avg_time, label = as.character(start_date))) +
  geom_line() +
  geom_point() +
  geom_line(aes(y = avg_time_all), linetype = "dashed", color = "red") +
  geom_point(aes(y = avg_time_all)) +
  ggrepel::geom_label_repel() +
  facet_wrap(vars(rush), scales = "free") +
  theme_minimal()
```


#### With Direction (for Links)

```{r}
# Average trip time and number of trips per aggregated arrival_time per direction
trip_time_arrival_dir <- trip_times_agg %>%
  group_by(arrival_time, direction) %>%
  summarise(avg_time = mean(trip_time),
            no_trips = n(),
            rush = unique(rush)) %>%
  ungroup()

# Average trip time per time and direction (hour and minute of the day)
trip_time_hm_dir <- trip_times_agg %>%
  group_by(time, direction) %>% 
  summarise(avg_time = mean(trip_time),
            no_trips = n(),
            rush = unique(rush),
            no_days = n_distinct(start_date),
            avg_per_day = no_trips/n_distinct(trip_times_agg$start_date)) %>% 
  ungroup()

# Average trip time per day per peak time per direction
trip_times_peaks_dir <- trip_times %>% 
  filter(rush %in% c("morning", "evening")) %>% 
  group_by(start_date, rush, direction) %>% 
  summarise(avg_time_day = mean(trip_time)) %>% 
  ungroup() %>% 
  group_by(rush, direction) %>% 
  mutate(avg_time_all_peak = mean(avg_time_day)) %>% 
  ungroup()

# Average trip time per day per peak time per hour per direction
trip_times_peaks_hours_dir <- trip_times %>% 
  filter(rush %in% c("morning", "evening")) %>%
  mutate(hour = hour(arrival_time)) %>% 
  group_by(start_date, rush, hour, direction) %>% 
  summarise(avg_time = mean(trip_time)) %>% 
  ungroup() %>% 
  group_by(rush, direction, hour) %>% 
  mutate(avg_time_all = mean(avg_time)) %>% 
  ungroup()

# Day with largest trip time per hour
trip_times_peaks_hours_largest_day_dir <- trip_times_peaks_hours_dir %>% 
  group_by(rush, hour, direction) %>% 
  filter(avg_time == max(avg_time)) %>% 
  ungroup()
```

```{r}
ggplot(filter(trip_time_hm_dir, rush == "neither"), aes(x = time, y = avg_per_day)) +
  geom_col(color = "grey", alpha = 0.3) +
  geom_col(data = filter(trip_time_hm, rush %in% c("morning", "evening")), color = "grey") +
  scale_x_time(breaks = as_hms(c("00:00:00", "06:00:00", "08:00:00", "10:00:00",
                                 "15:00:00", "17:00:00", "19:00:00")),
               labels = c("00", "6", "8", "10", "15", "17", "19")) +
  theme_minimal()

ggplot(trip_times_peaks_dir, aes(start_date, avg_time_day)) +
  geom_line() +
  geom_point() +
  geom_hline(aes(yintercept = avg_time_all_peak), linetype = "dashed", color = "red") +
  facet_wrap(vars(rush), scales = "free_y") +
  theme_minimal()

trip_times_peaks_hours_dir %>% 
  filter(rush == "morning") %>% 
  ggplot(aes(start_date, avg_time)) +
  geom_line() +
  geom_point() +
  geom_hline(aes(yintercept = avg_time_all), linetype = "dashed", color = "red") +
  facet_wrap(vars(hour), scales = "free_y") +
  theme_minimal()

trip_times_peaks_hours_dir %>% 
  filter(rush == "evening") %>% 
  ggplot(aes(start_date, avg_time)) +
  geom_line() +
  geom_point() +
  geom_hline(aes(yintercept = avg_time_all), linetype = "dashed", color = "red") +
  facet_wrap(vars(hour), scales = "free_y") +
  theme_minimal()

trip_times_peaks_hours_largest_day_dir %>% 
  ggplot(aes(hour, avg_time, label = as.character(start_date))) +
  geom_line() +
  geom_point() +
  geom_line(aes(y = avg_time_all), linetype = "dashed", color = "red") +
  geom_point(aes(y = avg_time_all)) +
  ggrepel::geom_label_repel() +
  facet_wrap(vars(rush), scales = "free") +
  theme_minimal()
```


### Congestion

```{r}
links_agg <- link_stats  %>% 
  mutate(logtime = ceiling_date(logtime, "15 mins")) %>% 
  mutate(time = hms::as_hms(logtime), .after = logtime)

# Average congestion per link per logtime per direction
ind_link_cong_logtime <- links_agg %>%
  group_by(logtime, direction, linkid) %>%
  summarise(avg_congestion = mean(congestion)) %>%
  ungroup()

# Average congestion of all links per logtime per direction (average full road congestion)
links_cong_logtime <- links_agg %>%
  group_by(logtime, direction) %>%
  summarise(avg_congestion = mean(congestion))

# Average congestion per link per time
ind_link_cong_time <- links_agg %>% 
  group_by(time, linkid, direction) %>% 
  summarise(avg_congestion = mean(congestion)) %>% 
  ungroup()

# Average congestion of all links per time (average full road congestion)
links_cong_time <- links_agg %>% 
  group_by(time, direction) %>% 
  summarise(avg_congestion = mean(congestion))
```

## Compare

```{r}
compare_trips_links <- function(timeframe = "15 minutes", plot = "line", measure = congestion){
  trip_times_agg <- trip_times %>% 
  mutate(arrival_time = ceiling_date(arrival_time, timeframe)) %>% 
  mutate(time = hms::as_hms(arrival_time), .after = arrival_time)

  links_agg <- link_stats  %>% 
  mutate(logtime = ceiling_date(logtime, timeframe)) %>% 
  mutate(time = hms::as_hms(logtime), .after = logtime)

  if (plot == "line") {
    
      trip_time_hm_dir <- trip_times_agg %>%
        group_by(time, direction) %>% 
        summarise(avg_time = mean(trip_time)) %>% 
        ungroup()
      
      links_cong_time <- links_agg %>% 
        group_by(time, direction) %>% 
        summarise(avg_congestion = mean({{measure}}))
      
      trip_time_cong_links <- trip_time_hm_dir %>% 
        full_join(links_cong_time)

      trip_time_cong_links_pivot <- trip_time_cong_links %>%
        pivot_longer(cols = avg_time:avg_congestion, names_to = "stat", values_to = "value") %>% 
        mutate(direction = recode(direction, from_city = "From City", to_city = "To City"),
               stat = recode(stat, avg_congestion = "Avg Congestion", avg_time = "Avg Time (secs)"))
      
      trip_time_cong_links_pivot_mor_rush <- trip_time_cong_links_pivot %>% 
        filter(between(time, as_hms("06:00:00"), as_hms("10:00:00")))
      
      trip_time_cong_links_pivot_eve_rush <- trip_time_cong_links_pivot %>% 
        filter(between(time, as_hms("15:00:00"), as_hms("19:00:00")))
      
      ggplot() +
        geom_line(data = trip_time_cong_links_pivot, aes(x = time, y = value), alpha = 0.2) +
        geom_line(data = trip_time_cong_links_pivot_mor_rush, aes(x = time, y = value), color = "blue", size = 0.5) +
        geom_line(data = trip_time_cong_links_pivot_eve_rush, aes(x = time, y = value), color = "blue", size = 0.5) +
        annotate("rect", xmin = as_hms("06:00:00"), xmax = as_hms("10:00:00"), ymin = -Inf, ymax = Inf,
        fill = "red", alpha = .1) +
        annotate("rect", xmin = as_hms("15:00:00"), xmax = as_hms("19:00:00"), ymin = -Inf, ymax = Inf,
        fill = "red", alpha = .1) +
        facet_grid(rows = vars(stat), cols = vars(direction), scales = "free_y") +
        scale_x_time(breaks = as_hms(c("00:00:00", "06:00:00", "08:00:00", "10:00:00", 
                                       "15:00:00", "17:00:00", "19:00:00")),
                     labels = c("00", "6", "8", "10", "15", "17", "19")) +
        labs(x = "Time", y = "") +
        theme_minimal()
  } else if (plot == "scatter") {
    
      trip_time_arrival_dir <- trip_times_agg %>%
        group_by(arrival_time, direction) %>%
        summarise(avg_time = mean(trip_time)) %>%
        ungroup()
      
      links_cong_logtime <- links_agg %>%
        group_by(logtime, direction) %>%
        summarise(avg_congestion = mean({{measure}}))
      
      trip_time_cong_links_scatter <- trip_time_arrival_dir %>% 
        inner_join(links_cong_logtime, by = c("arrival_time" = "logtime", "direction")) %>% 
        filter(between(as_hms(arrival_time), as_hms("06:00:00"), as_hms("10:00:00")) |
                 between(as_hms(arrival_time), as_hms("15:00:00"), as_hms("19:00:00"))) %>% 
         mutate(rush = if_else(between(as_hms(arrival_time), as_hms("06:00:00"), as_hms("10:00:00")),
                        "morning", "evening"))

      ggplot(trip_time_cong_links_scatter, aes(x = avg_congestion, y = avg_time)) +
        geom_point() +
        geom_smooth(se = FALSE) +
        facet_grid(vars(direction), vars(rush)) +
        labs(x = "Avg Congestion", y = "Avg Time (secs)") +
        theme_minimal()
  }
}
```
