---
title: "South Rd Analysis"
author: "Ibrahim Al-Hindi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Libraries
library(tidyverse)
library(here)
library(lubridate)
library(ggmap)
library(sf)
library(leaflet)
library(geosphere)
library(geodist)
```

```{r}
# Data
sites_raw <- read_csv(here("data/addinsight/addinsight_prod.btsites.csv.csv"))
#links_raw <- read_csv(here("data/addinsight/addinsight_prod.btlinks.csv.csv"))
links_south_rd <- read_csv(here("data/South-Rd/BT Links - South Rd.csv")) 
```

# Data Wrangling

```{r}
# Sites
## Remove duplicates
sites <- sites_raw %>% 
  distinct(id, .keep_all = TRUE)

rm(sites_raw)

## DF with sites and coordinates only
sites_coords <- sites %>% 
  select(id, longitude, latitude)

# Links
# links <- links_raw %>% 
#   distinct(id, .keep_all = TRUE)
# 
# rm(links_raw)

## Links DF for leaflet
### add origin site coordinates
# links_origin <- links %>% 
#   left_join(sites_coords, by = c("originid" = "id"))
# 
# ### add destination site coordinates
# links_dest <- links %>% 
#   left_join(sites_coords, by = c("destid" = "id"))
# 
# ### Row bind links_south_origin and links_south_dest
# links_leaflet <- bind_rows("origin" = links_origin, "dest" = links_dest, .id = "point") %>% 
#   arrange(id)

# Links_south_rd
links_south_rd <- links_south_rd %>% 
  rename_with(tolower) %>% 
  mutate(latitude = round(latitude, 5),
         longitude = round(longitude, 5))
```

# Getting Information for Analysis

## Identify Sites

Select sites from map on South Road between Anzac Highway and Ayliffs Road

```{r}
sites %>% 
    leaflet() %>% 
    addTiles() %>% 
    addCircles(label = ~ id, fillOpacity = 1)
```

Use Google maps to determine coordinates at each intersection of South Road required and get the sites within those coordinates

```{r}
sites_south <- sites %>% 
  filter(str_detect(tolower(name), pattern = "south road") |
           str_detect(tolower(instance_id), pattern = "south road"),
         between(longitude, 138.5710, 138.5763),
         between(latitude, -35.0116, -34.9420))

# Map to double check
sites_south %>% 
    leaflet() %>% 
    addTiles() %>% 
    addCircles(label = ~ id, fillOpacity = 1)
```

## Identify Links

```{r}
# Add start and end longitudes for each link and whether link going down map or up
links_south_rd_dir <- links_south_rd %>% 
  group_by(linkid) %>%
  arrange(ordernumber, .by_group = TRUE) %>% 
  mutate(start_lat = ifelse(ordernumber == 0, latitude, NA),
         end_lat = ifelse(ordernumber == max(ordernumber), latitude, NA)) %>% 
  fill(start_lat, .direction = "down") %>% 
  fill(end_lat, .direction = "up") %>%
  mutate(going_up = start_lat < end_lat) %>%  
  ungroup()
```

#### Build map going up

```{r}
links_up <- links_south_rd_dir %>% 
  filter(going_up == TRUE)

# Keep one row per linkid for now to see sequence of links
links_dist_up <- links_up %>% 
  distinct(linkid, .keep_all = TRUE) %>%
  # Build map from lower end of map to upper
  arrange(start_lat) %>% 
  # If two links have the same start_lat, keep the one that covers larger distance
  group_by(start_lat) %>% 
  filter(end_lat == max(end_lat)) %>%
  ungroup()
```

```{r}
# Identifying sequence of links with no overlaps

## end_lat to be compared to
flag_up <- links_dist_up$end_lat[1]

## Empty vector to hold linkid's identified in order
links_order_up <- vector("numeric")

## First link in the vector is the link with the lowest latitude
links_order_up[1] <- links_dist_up$linkid[1]

n <- 2

for (i in 2:nrow(links_dist_up)) {
  # Make sure new link lat starts after flag lat ends
  if (links_dist_up$start_lat[i] > flag_up) {
    # Add linkid
    links_order_up[n] <- links_dist_up$linkid[i]
    # Update flag
    flag_up <- links_dist_up$end_lat[i]
    
    n <- n+1
  }
}
```

```{r}
links_map_up <- links_south_rd_dir %>%
  filter(linkid %in% links_order_up) %>% 
  arrange(start_lat, ordernumber)

links_colors <- c("green","yellow")

n <- 1

temp_map_up <- leaflet() %>% 
  addTiles()

# Iterate over links to add polyline of each link to the map
for (link in unique(links_map_up$linkid)) {
  map_df <- links_map_up %>% 
    filter(linkid == link)
  
  temp_map_up <- temp_map_up %>% 
    addPolylines(data = map_df, lng = ~longitude, lat = ~latitude, color = links_colors[n], label = ~linkid, opacity = 0.3)
  
  # Switch colors
  if (n == 1) {
    n <- 2
  } else {
    n <- 1
  }
}

temp_map_up

# Missing link between Southern Avenue and Celtic Avenue. Locate a link between the two
link_southern_celt_up <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "southern"),
         str_detect(tolower(name), "celtic"),
         going_up == TRUE)

# Missing link between Daws Road and Corunna Avenue. Locate a link between the two
link_daws_cor_up <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "daws"),
         str_detect(tolower(name), "corunna"),
         going_up == TRUE)

# Missing link between John Street and Barwell Avenue. Locate a link between the two
link_john_bar_up <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "john"),
         str_detect(tolower(name), "barwell"),
         going_up == TRUE)

# Check links are correct
temp_map_up %>%
  addPolylines(data = link_southern_celt_up, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3) %>%
  addPolylines(data = link_daws_cor_up, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3) %>% 
  addPolylines(data = link_john_bar_up, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3)

# Combine missing links with map links up DF and plot
links_map_up <- links_map_up %>% 
  rbind(link_southern_celt_up, link_daws_cor_up, link_john_bar_up)

# Output final map up
map_up <- leaflet() %>% 
  addTiles()

for (link in unique(links_map_up$linkid)) {
  map_df <- links_map_up %>% 
    filter(linkid == link)
  
  map_up <- map_up %>% 
    addPolylines(data = map_df, lng = ~longitude, lat = ~latitude, color = "green", opacity = 1)
}

map_up
```

#### Build map going down

```{r}
# Same process as map going up above

links_down <- links_south_rd_dir %>% 
  filter(going_up == FALSE)

links_dist_down <- links_down %>% 
  distinct(linkid, .keep_all = TRUE) %>%
  arrange(-start_lat) %>% 
  group_by(start_lat) %>% 
  filter(end_lat == min(end_lat)) %>%
  ungroup()

flag_down <- links_dist_down$end_lat[1]

links_order_down <- vector("numeric")

links_order_down[1] <- links_dist_down$linkid[1]

n <- 2

for (i in 2:nrow(links_dist_down)) {
  if (links_dist_down$start_lat[i] < flag_down) {
    
    links_order_down[n] <- links_dist_down$linkid[i]
    
    flag_down <- links_dist_down$end_lat[i]
    
    n <- n+1
  }
}

links_map_down <- links_south_rd_dir %>%
  filter(linkid %in% links_order_down) %>% 
  arrange(-start_lat, ordernumber)

n <- 1

temp_map_down <- leaflet() %>% 
  addTiles()

for (link in unique(links_map_down$linkid)) {
  map_df <- links_map_down %>% 
    filter(linkid == link)
  
  temp_map_down <- temp_map_down %>% 
    addPolylines(data = map_df, lng = ~longitude, lat = ~latitude, color = links_colors[n], label = ~linkid, opacity = 0.3)
  
  if (n == 1) {
    n <- 2
  } else {
    n <- 1
  }
}

temp_map_down

# Missing link between Walsh Avenue and Celtic Avenue. Locate a link between the two
link_walsh_celt_down <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "walsh"),
         str_detect(tolower(name), "celtic"),
         going_up == FALSE)

# Missing link between Daws Road and Corunna Avenue. Locate a link between the two
link_daws_cor_down <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "daws"),
         str_detect(tolower(name), "corunna"),
         going_up == FALSE)

# Missing link between Edward Street and Albert Street. Locate a link between the two
link_edw_alb_down <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "edward"),
         str_detect(tolower(name), "albert"),
         going_up == FALSE)

# Missing link between Anzac Highway and Everard Avenue Locate a link between the two
link_anz_ever_down <- links_south_rd_dir %>%
  filter(str_detect(tolower(name), "anzac"),
         str_detect(tolower(name), "everard"),
         going_up == FALSE)

# Check links are correct
temp_map_down %>%
  addPolylines(data = link_walsh_celt_down, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3) %>%
  addPolylines(data = link_daws_cor_down, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3) %>% 
  addPolylines(data = link_edw_alb_down, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3) %>% 
  addPolylines(data = link_anz_ever_down, lng = ~longitude, lat = ~latitude, color = "red", label = ~linkid, opacity = 0.3)

# Combine missing links with map links down DF and plot
links_map_down <- links_map_down %>% 
  rbind(link_walsh_celt_down, link_daws_cor_down, link_edw_alb_down, link_anz_ever_down)

# Output final map down
map_down <- leaflet() %>% 
  addTiles()

for (link in unique(links_map_down$linkid)) {
  map_df <- links_map_down %>% 
    filter(linkid == link)
  
  map_down <- map_down %>% 
    addPolylines(data = map_df, lng = ~longitude, lat = ~latitude, color = "red", opacity = 1)
}

map_down
```

```{r}
# Plot links from both directions
map_both <- leaflet() %>% 
  addTiles()

# Add links up map
for (link in unique(links_map_up$linkid)) {
  map_df <- links_map_up %>% 
    filter(linkid == link)
  
  map_both <- map_both %>% 
    addPolylines(data = map_df, lng = ~longitude, lat = ~latitude, color = "green", opacity = 1)
}

# Add links down map
for (link in unique(links_map_down$linkid)) {
  map_df <- links_map_down %>% 
    filter(linkid == link)
  
  map_both <- map_both %>% 
    addPolylines(data = map_df, lng = ~longitude, lat = ~latitude, color = "red", opacity = 1)
}

map_both
```



